# Generated by Django 4.2.2 on 2023-10-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='brief',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
